---
- name: "Archon Ansible Helper"
  hosts: local
  connection: local

  roles:
    - role: mirrors
      tags: mirrors

    - role: oh-my-fish
      tags: oh-my-fish

    - role: wallpaper-rng
      tags: wallpaper-rng

  tasks:
    - name: Install VSCodium extensions
      command:
        cmd: "{{ ansible_env.HOME }}/.config/VSCodium/User/extensions-list.sh"
        creates: "{{ ansible_env.HOME }}/.config/VSCodium/User/.extensions_installed"
      tags:
        - vscodium
        
    - name: Tasks for all roles
      block:
        - name: Move archon from autostart
          command:
            cmd: "mv -f {{ ansible_env.HOME }}/.config/autostart/archon.desktop {{ ansible_env.HOME }}/.local/share/applications/archon.desktop"
            removes: "{{ ansible_env.HOME }}/.config/autostart/archon.desktop"
          become: true

        - name: Ensure logrotate is present
          community.general.pacman:
            name: logrotate
            state: present
            update_cache: yes
          become: true

        - name: Copy logrotate config for user logs
          template:
            src: logrotate.j2
            dest: "/etc/logrotate.d/{{ ansible_env.USER }}"
          become: true
          
      tags:
        - mirrors
        - oh-my-fish
        - wallpaper-rng
        - vscodium
